### ISSUE TITLE
Wrong createVersion summary

### ISSUE THREAD

**Issue by kwiatek-kainos** [lukaszbudnik/migrator#290]
I've applied DB migrations and the operation ended successfully.
The migration was suspended for some time due to a secondary transaction.
After the successful migration I got the following summary.
```json
      "summary": {                                                                                                                                                                                
        "startedAt": "2021-09-15T11:08:00.162242499Z",                                                                                                                                            
        "duration": -1948086662,                                                                                                                                                                  
        "tenants": 6,                                                                                                                                                                             
        "singleMigrations": 0,                                                                                                                                                                    
        "tenantMigrationsTotal": 0,                                                                                                                                                               
        "migrationsGrandTotal": 0,                                                                                                                                                                
        "singleScripts": 8,                                                                                                                                                                       
        "tenantScriptsTotal": 246,                                                                                                                                                                
        "scriptsGrandTotal": 254                                                                                                                                                                  
      }                                                                                                                                                                                           
```
where the duration is obviously wrong - it's negative.

I was wondering why exactly we cast to int32 in the following passage:
https://github.com/lukaszbudnik/migrator/blob/5913c8f51bf4df0fc493f4efa39526cc306f7bc5/db/db.go#L480
I presume that `time.Since()` gave the right calculation but it got broken further down the line.

**Comment by lukaszbudnik** [comment]
thanks @kwiatek-kainos for reporting this issue. `time.Since()` returns float64 and I cast it to int32 because it looks better in final JSON result than float64 formatted in scientific notation 1.2e7.

It looks like the other transaction blocked migratory for so long that Since() returned so big number that casting it to in32 caused overflow and the result was a negative number.

We can fix it in two ways:
- convert duration to Seconds using `Seconds()` method and leave it as int32
- convert duration to float, leave it as milliseconds, have JSON formatting large numbers in scientific notation 1.2e7

Which option would you prefer? I honestly would go for converting duration from milliseconds to seconds and leave them as int32 in JSON so that they are easier for humans to read.

**Comment by kwiatek-kainos** [comment]
The first option, seconds, sounds good enough for me.

**Comment by lukaszbudnik** [comment]
I actually went with a mixed approach:

- duration is now in seconds -> the duration is now 1e9 times smaller number
- migratory is fast and many migrations were applied in less than a second and casting float64 to int32 was rounding them to 0, that is why I decided to convert duration to float64. Since duration is now in seconds and not milliseconds the JSON output looks much better/user-friendly and doesn't use the scientific notation floats.
